Throw std::runtime_error instead of std::exception, to fix GCC errors
Fixed GCC compile errors on throw std::exception("<some string>"), reported at
https://travis-ci.com/github/bldrvnlw/conan-ImageViewerPlugin

Which said something like:
> error: no matching function for call to ‘std::exception::exception(QByteArray)