Fix error: no matching constructor for initialization of 'QVector<uint>'
Worked around an error on the CI, which was triggered by the fact that the CI still uses an old version of Qt (5.12.4), at Xcode: xcode10.3:

> ImageViewerPlugin.cpp:77:24: error: no matching constructor for initialization of 'QVector<uint>'

https://travis-ci.com/github/bldrvnlw/conan-ImageViewerPlugin/jobs/367085106#L8362